### ISSUE TITLE
hk delete case doesn't work

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/housekeeper#23]
```bash
$ housekeeper delete case cust002-F0001356_14034-2
```

```python
Traceback (most recent call last):
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/bin/housekeeper", line 11, in <module>
    load_entry_point('housekeeper==1.1.0', 'console_scripts', 'housekeeper')()
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/housekeeper/store/cli.py", line 201, in delete_case
    family_id=case_obj.family_id)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/housekeeper/store/api.py", line 65, in samples
    query = query.filter_by(customer=customer)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 1345, in filter_by
    for key, value in kwargs.items()]
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/sqlalchemy/orm/base.py", line 383, in _entity_descriptor
    (description, key)
sqlalchemy.exc.InvalidRequestError: Entity '<class 'housekeeper.store.models.Sample'>' has no property 'customer'
```

**Comment by robinandeer** [comment]
I was able to delete this using the GUI!

I didn't check before which samples it was related to but otherwise the cascade rules seems to work :)

Also I've updated the functions that were old and the cascade rules. Can't find them back in the GUI tho and the migration script is empty lol
