### ISSUE TITLE
include fastq files

### ISSUE THREAD

**Issue by b4ckm4n** [Clinical-Genomics/housekeeper#35]
When a bioinformatician wants to include fastq files from a sample on two 2500 flowcells, housekeeper throws an error:

```
$ housekeeper include ADM1101A6
2018-05-22 13:45:37 rastapopoulos.scilifelab.se housekeeper.include[27558] INFO created new bundle version dir: /mnt/hds/proj/bioinfo/bundles/ADM1101A6/2018-02-15
2018-05-22 13:45:37 rastapopoulos.scilifelab.se housekeeper.include[27558] INFO linked file: /mnt/hds/proj/bioinfo/DEMUX/150724_D00410_0168_BH3JVYBCXX/Unaligned-Y101I8Y101/Project_545414/Sample_ADM1101A6_XTF06/ADM1101A6_XTF06_GTCGTAGA_L001_R1_001.fastq.gz -> /mnt/hds/proj/bioinfo/bundles/ADM1101A6/2018-02-15/ADM1101A6_XTF06_GTCGTAGA_L001_R1_001.fastq.gz
2018-05-22 13:45:37 rastapopoulos.scilifelab.se housekeeper.include[27558] INFO linked file: /mnt/hds/proj/bioinfo/DEMUX/150724_D00410_0168_BH3JVYBCXX/Unaligned-Y101I8Y101/Project_545414/Sample_ADM1101A6_XTF06/ADM1101A6_XTF06_GTCGTAGA_L001_R2_001.fastq.gz -> /mnt/hds/proj/bioinfo/bundles/ADM1101A6/2018-02-15/ADM1101A6_XTF06_GTCGTAGA_L001_R2_001.fastq.gz
2018-05-22 13:45:37 rastapopoulos.scilifelab.se housekeeper.include[27558] INFO linked file: /mnt/hds/proj/bioinfo/DEMUX/150724_D00410_0168_BH3JVYBCXX/Unaligned-Y101I8Y101/Project_545414/Sample_ADM1101A6_XTF06/ADM1101A6_XTF06_GTCGTAGA_L002_R1_001.fastq.gz -> /mnt/hds/proj/bioinfo/bundles/ADM1101A6/2018-02-15/ADM1101A6_XTF06_GTCGTAGA_L002_R1_001.fastq.gz
2018-05-22 13:45:37 rastapopoulos.scilifelab.se housekeeper.include[27558] INFO linked file: /mnt/hds/proj/bioinfo/DEMUX/150724_D00410_0168_BH3JVYBCXX/Unaligned-Y101I8Y101/Project_545414/Sample_ADM1101A6_XTF06/ADM1101A6_XTF06_GTCGTAGA_L002_R2_001.fastq.gz -> /mnt/hds/proj/bioinfo/bundles/ADM1101A6/2018-02-15/ADM1101A6_XTF06_GTCGTAGA_L002_R2_001.fastq.gz
Traceback (most recent call last):
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/prod170926/bin/housekeeper", line 11, in <module>
    load_entry_point('housekeeper==2.2.4', 'console_scripts', 'housekeeper')()
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/prod170926/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/prod170926/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/prod170926/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/prod170926/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/prod170926/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/prod170926/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/prod170926/lib/python3.6/site-packages/housekeeper/cli/include.py", line 32, in include
    include_version(context.obj['root'], version_obj)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/prod170926/lib/python3.6/site-packages/housekeeper/include.py", line 30, in include_version
    os.link(file_obj_path.resolve(), new_path)
FileExistsError: [Errno 17] File exists: '/mnt/hds/proj/bioinfo/DEMUX/150724_D00410_0167_AH3KLYBCXX/Unaligned-Y101I8Y101/Project_545414/Sample_ADM1101A6_XTF06/ADM1101A6_XTF06_GTCGTAGA_L001_R1_001.fastq.gz' -> '/mnt/hds/proj/bioinfo/bundles/ADM1101A6/2018-02-15/ADM1101A6_XTF06_GTCGTAGA_L001_R1_001.fastq.gz'
```

Fastq files of the first flowcell gets successfully adde but the fastq files of the second flowcell throw an error, because the fastq file names for both flowcells are the same.

Expected functionality: Files get successfully included.

Suggested solution: quick and dirty script to rename fastq files. (add the FC name into the the filename)

**Comment by moonso** [comment]
Hi @b4ckm4n , is this still a problem?

**Comment by b4ckm4n** [comment]
I haven't run into this problem again, so given that it has been two years I think this at some point was remedied.

So No, not a problem anymore :)
